# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logistic_CPP <- function(x) {
    .Call(`_OccDesign_logistic_CPP`, x)
}

loglik_cpp <- function(pars, y, M, X_psi, X_p, cov_psi, cov_p, y_occupied, occ, occ_all, sumM) {
    .Call(`_OccDesign_loglik_cpp`, pars, y, M, X_psi, X_p, cov_psi, cov_p, y_occupied, occ, occ_all, sumM)
}

gr_loglik_cpp <- function(pars, y, M, X_psi, X_p, cov_psi, cov_p, y_occupied, occ, occ_all, sumM) {
    .Call(`_OccDesign_gr_loglik_cpp`, pars, y, M, X_psi, X_p, cov_psi, cov_p, y_occupied, occ, occ_all, sumM)
}

